<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends EntityRepository
{

    public function getAlbums()
    {
        $sql = "
            SELECT
              al.*,
              substring_index(
                  (
                    SELECT GROUP_CONCAT(img.fileName SEPARATOR ',')
                    FROM (
                           SELECT *
                           FROM images
                         ) img
                    WHERE img.album_id = al.id
                  ),
              ',', 10) as photos
            FROM albums al
        ";

        $stmt = $this->getEntityManager()
                     ->getConnection()
                     ->prepare($sql);

        $stmt->execute();
        return $stmt->fetchAll();
    }

}
